import { Dispatch, SetStateAction } from "react";
import Image from "next/image";

export const Tutorial = ({
  setShowModal,
}: {
  setShowModal: Dispatch<SetStateAction<boolean>>;
}) => {
  return (
    <div
      className="modal modal-bottom sm:modal-middle modal-open"
      onClick={() => {
        setShowModal(false);
      }}
    >
      <div
        className="modal-box"
        onClick={(e) => {
          e.stopPropagation();
        }}
      >
        <label
          className="btn btn-sm btn-circle absolute right-2 top-2"
          onClick={() => {
            setShowModal(false);
          }}
        >
          ✕
        </label>
        <h2 className="font-bold text-lg">What is Hit And Blow onChain?</h2>
        <div className="py-4 prose">
          <p className="mb-4">
            Hit & Blow is a popular code-breaking PvP game. <br />
            The game is played in turns by two players who aim to decipher the
            opponent's secret number.
          </p>
          <p className="mb-4">
            Hit and Blow Onchain is a fully on-chain version of it.
            <br />
            Zero Knowledge proof enables the game to ensure the integrity of the
            game without any trusted third party.
          </p>
          <h2 className="font-bold text-lg">How to play?</h2>
          <ul>
            <li>Register</li>
            <p className="text-sm mt-0">
              After your registration, an auto play bot will be activated as
              your opponent.
            </p>
            <div className="text-center">
              <Image
                src="/hb1.png"
                alt="hb1"
                width="400"
                height="200"
                objectFit="contain"
              />
            </div>
            <li>Commit solution hash</li>
            <p className="text-sm mt-0">
              Choose a 4-digit number from digits 0 to 9 without repetition,
              then hash it with a salt and commit it.
            </p>
            <div className="text-center">
              <Image
                src="/hb2.png"
                alt="hb2"
                width="400"
                height="200"
                objectFit="contain"
              />
            </div>

            <li>Submit guess and proof</li>
            <p className="text-sm mt-0 mb-0">
              Submit your guess of the opponent's secret number and the proof of
              the number of hits and blows for the opponent's guess. The proof
              generated by zkSNARK ensures your count is valid.
            </p>
            <p className="italic text-xs mt-0">
              <br />
              Hits: matching digits on correct positions.
              <br />
              Blows: matching digits on wrong positions.
            </p>
            <div className="text-center">
              <Image
                src="/hb3.png"
                alt="hb3"
                width="400"
                height="200"
                objectFit="contain"
              />
            </div>
            <li>Reveal your solution</li>
            <p className="text-sm mt-0">
              Finally if you won the game, you should reveal your solution
              because only your solution hash is recorded on-chain but not your
              solution itself.
            </p>
            <div className="text-center">
              <Image
                src="/hb4.png"
                alt="hb4"
                width="400"
                height="200"
                objectFit="contain"
              />
            </div>
          </ul>
        </div>
      </div>
    </div>
  );
};
